<?php

namespace App\Http\Controllers;

use App\Models\DietPlan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DietPlanController extends Controller
{
    public function index()
    {
        $userGoal = null;
        $followingDietId = null;
        $dietDay = 1;

        if (Auth::check()) {
            $profile = Auth::user()->profile;
            $userGoal = $profile?->goal;
            $followingDietId = $profile?->following_diet_id;
            
            if ($profile?->following_diet_started_at) {
                $dietDay = now()->diffInDays($profile->following_diet_started_at) + 1;
            }
        }

        $diets = DietPlan::all()->sortBy(function ($plan) use ($userGoal) {
            return $plan->goal === $userGoal ? 0 : 1;
        })->values();

        return view('diets.index', compact('diets', 'userGoal', 'followingDietId', 'dietDay'));
    }

    public function follow(DietPlan $diet)
    {
        if (!Auth::check()) {
            return redirect()->route('login');
        }

        Auth::user()->profile()->update([
            'following_diet_id' => $diet->id,
            'following_diet_started_at' => now(),
        ]);

        return back()->with('success', "You are now following the {$diet->title} plan!");
    }

    public function show(DietPlan $diet)
    {
        $diet->load('meals');
        return view('diets.show', compact('diet'));
    }

    public function download(DietPlan $diet)
    {
        $content  = "╔══════════════════════════════════╗\n";
        $content .= "║     FITCORE DIET PLAN             ║\n";
        $content .= "╚══════════════════════════════════╝\n\n";
        $content .= "Plan:             {$diet->title}\n";
        $content .= "Daily Calories:   {$diet->daily_calories} kcal\n";
        $content .= "Goal:             " . ucfirst(str_replace('_', ' ', $diet->goal ?? 'General')) . "\n";
        $content .= "Description:      {$diet->description}\n";
        $content .= "\n────────────────────────────────────\n";
        $content .= "MEAL PLAN\n";
        $content .= "────────────────────────────────────\n\n";

        // Ensure $meals is an array (handle cases where meals_json might be a string or invalid)
        $meals = $diet->meals_json;
        if (is_string($meals)) {
            $meals = json_decode($meals, true);
        }

        if (!is_array($meals)) {
            $meals = [
                'Breakfast' => 'Oatmeal & Eggs',
                'Lunch'     => 'Chicken Breast & Brown Rice',
                'Dinner'    => 'Salmon & Asparagus',
            ];
        }

        foreach ($meals as $mealType => $food) {
            // Each food item can be comma-separated — display one per line
            $items = array_map('trim', explode(',', $food));
            $content .= "► {$mealType}:\n";
            foreach ($items as $item) {
                $content .= "    • {$item}\n";
            }
            $content .= "\n";
        }

        $content .= "────────────────────────────────────\n";
        $content .= "Generated by FitCore | " . now()->format('d M Y') . "\n";

        $filename = strtolower(str_replace(' ', '_', $diet->title)) . '_plan.txt';

        return response($content)
            ->header('Content-Type', 'text/plain')
            ->header('Content-Disposition', "attachment; filename=\"{$filename}\"");
    }
}
